### ISSUE TITLE
3D Secure required - using PHP server version

### ISSUE THREAD

**Issue by reddingwebpro** [stripe-samples/card-payment-charges-api#6]
This is a great example, and works for most card types except for when 3D Secure 2 is required, in those cases it fails with "Your card was declined. This transaction requires authentication." What is missing from this sample to make 3D Secure work?

**Comment by adreyfus-stripe** [comment]
@reddingwebpro You are correct, this example declines any transactions that require 3DS. You should use our new Payment Intents API (an API that sits on top of Charges) that helps you easily handle 3DS. 

https://github.com/stripe-samples/accept-a-card-payment 

I updated the README to hopefully make it clearer that this sample is deprecated in favor of the one I linked about. Let me know if you have other questions and sorry for the confusion!
